// Code generated by mockery v2.44.1. DO NOT EDIT.

package db

import (
	context "context"
	db "mnezerka/myspots-server/db"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: _a0
func (_m *MockClient) Connect(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClient_Expecter) Connect(_a0 interface{}) *MockClient_Connect_Call {
	return &MockClient_Connect_Call{Call: _e.mock.On("Connect", _a0)}
}

func (_c *MockClient_Connect_Call) Run(run func(_a0 context.Context)) *MockClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Connect_Call) Return(_a0 error) *MockClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Connect_Call) RunAndReturn(run func(context.Context) error) *MockClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Database provides a mock function with given fields: _a0
func (_m *MockClient) Database(_a0 string) db.Database {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 db.Database
	if rf, ok := ret.Get(0).(func(string) db.Database); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Database)
		}
	}

	return r0
}

// MockClient_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockClient_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
//   - _a0 string
func (_e *MockClient_Expecter) Database(_a0 interface{}) *MockClient_Database_Call {
	return &MockClient_Database_Call{Call: _e.mock.On("Database", _a0)}
}

func (_c *MockClient_Database_Call) Run(run func(_a0 string)) *MockClient_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Database_Call) Return(_a0 db.Database) *MockClient_Database_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Database_Call) RunAndReturn(run func(string) db.Database) *MockClient_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: _a0
func (_m *MockClient) Disconnect(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClient_Expecter) Disconnect(_a0 interface{}) *MockClient_Disconnect_Call {
	return &MockClient_Disconnect_Call{Call: _e.mock.On("Disconnect", _a0)}
}

func (_c *MockClient_Disconnect_Call) Run(run func(_a0 context.Context)) *MockClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Disconnect_Call) Return(_a0 error) *MockClient_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Disconnect_Call) RunAndReturn(run func(context.Context) error) *MockClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: _a0
func (_m *MockClient) Ping(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClient_Expecter) Ping(_a0 interface{}) *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping", _a0)}
}

func (_c *MockClient_Ping_Call) Run(run func(_a0 context.Context)) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(_a0 error) *MockClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func(context.Context) error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function with given fields:
func (_m *MockClient) StartSession() (mongo.Session, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 mongo.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() (mongo.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() mongo.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockClient_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
func (_e *MockClient_Expecter) StartSession() *MockClient_StartSession_Call {
	return &MockClient_StartSession_Call{Call: _e.mock.On("StartSession")}
}

func (_c *MockClient_StartSession_Call) Run(run func()) *MockClient_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_StartSession_Call) Return(_a0 mongo.Session, _a1 error) *MockClient_StartSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_StartSession_Call) RunAndReturn(run func() (mongo.Session, error)) *MockClient_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// UseSession provides a mock function with given fields: ctx, fn
func (_m *MockClient) UseSession(ctx context.Context, fn func(mongo.SessionContext) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for UseSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(mongo.SessionContext) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_UseSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseSession'
type MockClient_UseSession_Call struct {
	*mock.Call
}

// UseSession is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(mongo.SessionContext) error
func (_e *MockClient_Expecter) UseSession(ctx interface{}, fn interface{}) *MockClient_UseSession_Call {
	return &MockClient_UseSession_Call{Call: _e.mock.On("UseSession", ctx, fn)}
}

func (_c *MockClient_UseSession_Call) Run(run func(ctx context.Context, fn func(mongo.SessionContext) error)) *MockClient_UseSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(mongo.SessionContext) error))
	})
	return _c
}

func (_c *MockClient_UseSession_Call) Return(_a0 error) *MockClient_UseSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_UseSession_Call) RunAndReturn(run func(context.Context, func(mongo.SessionContext) error) error) *MockClient_UseSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
