// Code generated by mockery v2.44.1. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCursor is an autogenerated mock type for the Cursor type
type MockCursor struct {
	mock.Mock
}

type MockCursor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCursor) EXPECT() *MockCursor_Expecter {
	return &MockCursor_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: _a0, _a1
func (_m *MockCursor) All(_a0 context.Context, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCursor_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockCursor_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 interface{}
func (_e *MockCursor_Expecter) All(_a0 interface{}, _a1 interface{}) *MockCursor_All_Call {
	return &MockCursor_All_Call{Call: _e.mock.On("All", _a0, _a1)}
}

func (_c *MockCursor_All_Call) Run(run func(_a0 context.Context, _a1 interface{})) *MockCursor_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockCursor_All_Call) Return(_a0 error) *MockCursor_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCursor_All_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockCursor_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: _a0
func (_m *MockCursor) Close(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCursor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCursor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockCursor_Expecter) Close(_a0 interface{}) *MockCursor_Close_Call {
	return &MockCursor_Close_Call{Call: _e.mock.On("Close", _a0)}
}

func (_c *MockCursor_Close_Call) Run(run func(_a0 context.Context)) *MockCursor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCursor_Close_Call) Return(_a0 error) *MockCursor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCursor_Close_Call) RunAndReturn(run func(context.Context) error) *MockCursor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function with given fields: _a0
func (_m *MockCursor) Decode(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCursor_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockCursor_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - _a0 interface{}
func (_e *MockCursor_Expecter) Decode(_a0 interface{}) *MockCursor_Decode_Call {
	return &MockCursor_Decode_Call{Call: _e.mock.On("Decode", _a0)}
}

func (_c *MockCursor_Decode_Call) Run(run func(_a0 interface{})) *MockCursor_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockCursor_Decode_Call) Return(_a0 error) *MockCursor_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCursor_Decode_Call) RunAndReturn(run func(interface{}) error) *MockCursor_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields: _a0
func (_m *MockCursor) Next(_a0 context.Context) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCursor_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockCursor_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockCursor_Expecter) Next(_a0 interface{}) *MockCursor_Next_Call {
	return &MockCursor_Next_Call{Call: _e.mock.On("Next", _a0)}
}

func (_c *MockCursor_Next_Call) Run(run func(_a0 context.Context)) *MockCursor_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCursor_Next_Call) Return(_a0 bool) *MockCursor_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCursor_Next_Call) RunAndReturn(run func(context.Context) bool) *MockCursor_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCursor creates a new instance of MockCursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCursor {
	mock := &MockCursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
