// Code generated by mockery v2.44.1. DO NOT EDIT.

package db

import mock "github.com/stretchr/testify/mock"

// MockSingleResult is an autogenerated mock type for the SingleResult type
type MockSingleResult struct {
	mock.Mock
}

type MockSingleResult_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSingleResult) EXPECT() *MockSingleResult_Expecter {
	return &MockSingleResult_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: _a0
func (_m *MockSingleResult) Decode(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSingleResult_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockSingleResult_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - _a0 interface{}
func (_e *MockSingleResult_Expecter) Decode(_a0 interface{}) *MockSingleResult_Decode_Call {
	return &MockSingleResult_Decode_Call{Call: _e.mock.On("Decode", _a0)}
}

func (_c *MockSingleResult_Decode_Call) Run(run func(_a0 interface{})) *MockSingleResult_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSingleResult_Decode_Call) Return(_a0 error) *MockSingleResult_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSingleResult_Decode_Call) RunAndReturn(run func(interface{}) error) *MockSingleResult_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSingleResult creates a new instance of MockSingleResult. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSingleResult(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSingleResult {
	mock := &MockSingleResult{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
